spring.application.name=hospitalbackend

spring.datasource.url=jdbc:postgresql://dpg-d8a1vmgjs32c739mkpb0-a.singapore-postgres.render.com/hospitaldb_quyo
spring.datasource.username=hospitaluser
spring.datasource.password=8IJ7lMFIAYh1aJXOAs384AM2z9XFB3jg

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect